services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports: 
      - "7333:6333"  # ← đổi port ngoài thành 7333
      - "7334:6334"  # ← đổi port ngoài thành 7334

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: shc_elasticsearch
    restart: always
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - logger.level=error
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
        - "8200:9200"  # ← đổi port ngoài thành 8200
        - "8300:9300"  # ← đổi port ngoài thành 8300
